os: linux
dist: bionic
language: python  # python 环境启动比 Golang 耗时少，hugo 为编译好的二进制文件，语言环境不影响 hugo 执行

python:
  - "3.7"  # 指定 Python 3.7

git:
  depth: 1  # 只 clone 最后一次 commit ，加快速度
  quiet: true

env:
  global:
    # 设定 Github Pages 环境变量
    - GH_REF: github.com/he-sb/tech

# 分支白名单限制：只有 master 分支的提交才会触发构建
branches:
  only:
    - master
    
install:  # 安装依赖
  # 安装 hugo （version: v0.66.0）
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.66.0/hugo_extended_0.66.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo  # 生成网站
  
deploy:
  provider: pages  # 部署到 Github Pages
  skip-cleanup: true  # 必须为 true ，否则 Travis 会删除在构建期间创建的所有文件（即删除了要上传的文件）
  local-dir: public  # 被推送到 GitHub Pages 的目录，可以指定为当前目录的绝对路径或相对路径
  on:
    branch: master  # 博客源码所在分支
  target-branch: gh-pages  # 将 local-dir 强制推送到哪个分支（自定义，名称不能与源代码分支名相同），默认为 gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true  # 保持 target-branch 分支的提交记录