name: Github-Pages

# 在 master 分支更新时触发构建
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TZ: Asia/Shanghai
    steps:
      # 配置 git
      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 拉取源码
      - name: Clone Repository
        run:
          git clone --branch=master --quiet https://github.com/he-sb/tech.git site

      # 安装 hugo (v0.79.0)
      - name: Setup Hugo
        run: |
          wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.79.0/hugo_extended_0.79.0_Linux-64bit.deb && sudo dpkg -i hugo.deb
          hugo version

      # 构建网站
      - name: Build
        run:
          cd site && hugo --gc --minify --cleanDestinationDir

      # 部署至 GitHub Pages
      - name: Deploy
        env:
          SECRET: ${{ secrets.PERSONAL_TOKEN }}
          TARGET_REPO: "github.com/he-sb/tech.git"
          TARGET_BRANCH: "gh-pages"
        run: |
          cd site/public && git init
          git add .
          git commit -m "Update Blog By GitHub Actions With Build ${GITHUB_RUN_NUMBER}"
          git push --force --quiet "https://$SECRET@$TARGET_REPO" master:$TARGET_BRANCH
