name: Github-Pages

on:
  push:
    branches:
      - master  # 在 master 分支更新时触发构建

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2  # 拉取源码

      - name: Setup Hugo  # 使用指定版本的 hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.66.0'
          extended: true

      - name: Build  # 构建网站
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy  # 部署至 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}  # 使用 Personal Access Token
          publish_branch: gh-pages  # 部署至 gh-pages 分支
          force_orphan: true  # 不保留部署分支的提交历史
          commit_message: ${{ github.event.head_commit.message }}  # 使用源码的提交信息
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
