name: Github-Pages

on:
  push:
    branches:
      - master  # 在 master 分支更新时触发构建

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TZ: Asia/Shanghai
    steps:
      # - uses: actions/checkout@v1  # 拉取源码
      - name: Git Configuration  # 配置 git
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false

      - name: Clone Repository  # 拉取源码
        run: |
          git clone --branch=master --quiet https://github.com/he-sb/tech.git he-sb/tech
          cd he-sb/tech

      - name: Setup Hugo  # 使用指定版本的 hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.66.0'
          extended: true

      - name: Build  # 构建网站
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy  # 部署至 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}  # 使用 Personal Access Token
          publish_branch: gh-pages  # 部署至 gh-pages 分支
          force_orphan: true  # 不保留部署分支的提交历史
          commit_message: ${{ github.event.head_commit.message }}  # 使用源码的提交信息
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
