name: Github-Pages

on:
  push:
    branches:
      - master  # 在 master 分支更新时触发构建

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Git Configuration  # 配置 git
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false

      - name: Clone Repository  # 拉取源码
        run: |
          git clone --branch=master --quiet https://github.com/he-sb/tech.git he-sb/tech

      - name: Setup Hugo  # 安装 hugo (version: v0.66.0)
        run: |
          wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.66.0/hugo_extended_0.66.0_Linux-64bit.deb
          sudo dpkg -i hugo.deb
          hugo version

      - name: Build  # 构建网站
        run: |
          cd he-sb/tech
          hugo --gc --minify --cleanDestinationDir

      - name: Deploy  # 部署至 GitHub Pages
        env:
          SECRET: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          cd he-sb/tech/public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Blog By GitHub Actions With Build ${GITHUB_RUN_NUMBER}"
          git push --force --quiet "https://$SECRET@github.com/${GITHUB_REPOSITORY}" master:gh-pages
